version: "3.8"
services:
  database:
    image: postgres:latest
    container_name: database-prisma
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql
